### PR TITLE
Follow best practices for a Komodo addon

### PR DESCRIPTION
**Pull request by Naatan**
I did some slight refactoring to make the addon follow best practices for a Komodo addon.

The main difference for users will be that the dialog follows the UI styling and that they can still switch between different color pickers using the hidden pref.

### CODE REVIEW

**Comment by Defman21** [comment]
This PR would make me switch back to this color picker :)

**Comment by Defman21** [comment]
Or not. I've built the add-on from source of Nathan's fork and when I open the color picker, it's still the default for me.

```
> require('ko/prefs').getString('colorpicker_cid')
< String "@babobski.com/rgbaColorPicker;1"
```

**Comment by Defman21** [comment]
```
[2016-07-30 18:08:32,017] [ERROR] koSysUtils: Unable to load the colorpicker with CID: u'@babobski.com/rgbaColorPicker;1'
Traceback (most recent call last):
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/components/koSysUtils.py", line 378, in pickColorAsync
    getService(components.interfaces.koIColorPickerAsync)
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/python/xpcom/components.py", line 195, in getService
    return serviceManager.getServiceByContractID(self.contractid, _get_good_iid(iid))
  File "<XPCOMObject method 'getServiceByContractID'>", line 3, in getServiceByContractID
Exception: 2147746132 (NS_ERROR_FACTORY_NOT_REGISTERED)
```

**Comment by Naatan** [comment]
Yeah I had that problem too, but it disappeared after installing the old version again and then installing the new. I suspect the profile is caching part of the addon. The issue is not with the addon code but with Mozilla's broken addon system.

I kinda hoped the issue would not manifest itself for people doing a straight update though. Maybe increasing the version number could help? I'll play with it next week.

Should work fine on a clean profile.

**Comment by Defman21** [comment]
I'll try to increase the version and report back if it would help.

**Comment by Defman21** [comment]
That did **not** the trick.

**Comment by Naatan** [comment]
If you feel so inclined, see if you can figure out what file in the profile folder (likely under XRE) is caching the info. Deleting them should cause Komodo to get the information fresh (most of them are caches).

**Comment by Defman21** [comment]
Yeah I'm already trying to find out what's wrong there.

**Comment by Defman21** [comment]
I've tried a clean profile. Still getting the same error.

**Comment by Naatan** [comment]
That's odd, it worked fine for me. I'll dig next week. Will close this in the meantime.

**Pull request closed without merging**
